#!/usr/bin/env bash
# -----------------------------------
#| bgll.fullstackfullstock.com       |
#| github.com/babidiii               |
# -----------------------------------


#[[-------------------------------------------------------------------- Settings
set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes
# set -o xtrace  # for debug : could use bash -x prog instead 
#]]


link="https://raw.githubusercontent.com/Babidiii/dmoji/master/emoji-list.txt"

emoji=$(curl -s "${link}" | dmenu -i -l 20 -p "Emoji :" | cut -d '(' -f 2 | cut -d ')' -f1 | xargs echo -n )

if [[ $emoji == *".."* ]]; then
  echo "${emoji}" | tr -s '.' | sed 's/\./\n/g' | dmenu -i -l 5 -p "Choose:" | xargs echo -n | xclip -sel clip

else 
   echo -n "${emoji}" | xclip -sel clip
fi

