#!/usr/bin/env bash
# -----------------------------------
#| bgll.fullstackfullstock.com       |
#| github.com/babidiii               |
# -----------------------------------


#[[-------------------------------------------------------------------- Settings
set -o errexit   # abort on nonzero exitstatus
set -o nounset   # abort on unbound variable
set -o pipefail  # don't hide errors within pipes
#set -o xtrace  # for debug : could use bash -x prog instead
#]]

primary="$(xrandr -q | awk '/primary/{print $1}')"
secondary_choices="$(xrandr -q | awk '/ connected / && $3 != "primary" {printf "%s\n",$1}')"

dmenu_disp(){
  dmenu -i -b -nb "#000000" -nf "#999999" -sb "#000000" -sf "#ff650C" -p "$1"
}

main(){
  if [ $(echo "${secondary_choices}" | wc -l) -gt 1 ]; then 
    secondary=$(echo "$secondary_choices" | dmenu_disp "[$primary][ ? ]")
  else
    secondary="${secondary_choices}"
  fi

  choice=$(printf "above\nleft-of\nright-of\nbelow\nsame-as" | dmenu_disp "[$primary][$secondary]")
  xrandr --output "${primary}" --primary --mode 1920x1080 --output "${secondary}" --mode 1920x1080 "--${choice}" "${primary}"
}

main
